export const FETCH_TRACKS_START = 'FETCH_TRACKS_START'
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS'
export const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILURE'
export const ADD_NEW = 'ADD_NEW'