export const FETCH_TODO_START = "FETCH_TODO_START";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILUR = "FETCH_TODO_FAILUR";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_START = "ADD_TODO_START";
